services:
  standard:
    build:
      context: .
      additional_contexts:
        sdk: ../../sdk
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: python
        BASE_IMAGE_VERSION: 3.11
    image: bettmensch88/bettmensch.ai-default:local
  pytorch:
    build:
      context: .
      additional_contexts:
        sdk: ../../sdk
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: pytorch/pytorch
        BASE_IMAGE_VERSION: 2.2.2-cuda12.1-cudnn8-runtime
    image: bettmensch88/bettmensch.ai-pytorch:local
  pytorch-lightning:
    build:
      context: .
      additional_contexts:
        sdk: ../../sdk
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: pytorchlightning/pytorch_lightning
        BASE_IMAGE_VERSION: 2.3.3-py3.11-torch2.2-cuda12.1.0
    image: bettmensch88/bettmensch.ai-pytorch-lightning:local