import datetime
import os

import pytest
from bettmensch_ai.constants import COMPONENT_TYPE, PIPELINE_TYPE


@pytest.fixture
def test_output_dir():
    return os.path.join(".", "sdk", "test", "unit", "outputs")


@pytest.fixture
def test_mock_pipeline():
    class MockPipeline:
        type = PIPELINE_TYPE
        io_owner_name = PIPELINE_TYPE

    return MockPipeline()


@pytest.fixture
def test_mock_component():
    class MockComponent:
        type = COMPONENT_TYPE
        name = "mock-component-0"
        io_owner_name = f"{type}.{name}"

    return MockComponent()


@pytest.fixture
def test_hera_workflow_template_model():
    class MockHeraWorkflowTemplateModel:
        def dict(self):

            return {
                "api_version": None,
                "kind": None,
                "metadata": {
                    "annotations": None,
                    "cluster_name": None,
                    "creation_timestamp": datetime.datetime.now(),
                    "deletion_grace_period_seconds": None,
                    "deletion_timestamp": None,
                    "finalizers": None,
                    "generate_name": "pipeline-test-artifact-pipeline-",
                    "generation": 1,
                    "labels": {
                        "workflows.argoproj.io/creator": "system-serviceaccount-argo-argo-server"  # noqa: E501
                    },
                    "managed_fields": [
                        {
                            "api_version": "argoproj.io/v1alpha1",
                            "fields_type": "FieldsV1",
                            "fields_v1": {},
                            "manager": "argo",
                            "operation": "Update",
                            "subresource": None,
                            "time": datetime.datetime.now(),
                        }
                    ],
                    "name": "pipeline-test-artifact-pipeline-cw8pc",
                    "namespace": "argo",
                    "owner_references": None,
                    "resource_version": "38482",
                    "self_link": None,
                    "uid": "982b27a9-d8cb-4a79-a72a-b8dae4f14145",
                },
                "spec": {
                    "active_deadline_seconds": None,
                    "affinity": None,
                    "archive_logs": None,
                    "arguments": {
                        "artifacts": None,
                        "parameters": [
                            {
                                "default": None,
                                "description": None,
                                "enum": None,
                                "global_name": None,
                                "name": "a",
                                "value": "Param A",
                                "value_from": None,
                            }
                        ],
                    },
                    "artifact_gc": None,
                    "artifact_repository_ref": None,
                    "automount_service_account_token": None,
                    "dns_config": None,
                    "dns_policy": None,
                    "entrypoint": "bettmensch-ai-dag",
                    "executor": None,
                    "hooks": None,
                    "host_aliases": None,
                    "host_network": None,
                    "image_pull_secrets": None,
                    "metrics": None,
                    "node_selector": None,
                    "on_exit": None,
                    "parallelism": None,
                    "pod_disruption_budget": None,
                    "pod_gc": None,
                    "pod_metadata": None,
                    "pod_priority": None,
                    "pod_priority_class_name": None,
                    "pod_spec_patch": None,
                    "priority": None,
                    "retry_strategy": None,
                    "scheduler_name": None,
                    "security_context": None,
                    "service_account_name": None,
                    "shutdown": None,
                    "suspend": None,
                    "synchronization": None,
                    "template_defaults": None,
                    "templates": [
                        {
                            "active_deadline_seconds": None,
                            "affinity": None,
                            "archive_location": None,
                            "automount_service_account_token": None,
                            "container": None,
                            "container_set": None,
                            "daemon": None,
                            "dag": {
                                "fail_fast": None,
                                "target": None,
                                "tasks": [
                                    {
                                        "arguments": {
                                            "artifacts": None,
                                            "parameters": [
                                                {
                                                    "default": None,
                                                    "description": None,
                                                    "enum": None,
                                                    "global_name": None,
                                                    "name": "a",
                                                    "value": "{{workflow.parameters.a}}",  # noqa: E501
                                                    "value_from": None,
                                                }
                                            ],
                                        },
                                        "continue_on": None,
                                        "dependencies": None,
                                        "depends": None,
                                        "hooks": None,
                                        "inline": None,
                                        "name": "convert-to-artifact-0",
                                        "on_exit": None,
                                        "template": "convert-to-artifact",
                                        "template_ref": None,
                                        "when": None,
                                        "with_items": None,
                                        "with_param": None,
                                        "with_sequence": None,
                                    },
                                    {
                                        "arguments": {
                                            "artifacts": [
                                                {
                                                    "archive": None,
                                                    "archive_logs": None,
                                                    "artifact_gc": None,
                                                    "artifactory": None,
                                                    "azure": None,
                                                    "deleted": None,
                                                    "from_": "{{tasks.convert-to-artifact-0.outputs.artifacts.a_art}}",  # noqa: E501
                                                    "from_expression": None,
                                                    "gcs": None,
                                                    "git": None,
                                                    "global_name": None,
                                                    "hdfs": None,
                                                    "http": None,
                                                    "mode": None,
                                                    "name": "a",
                                                    "optional": None,
                                                    "oss": None,
                                                    "path": None,
                                                    "raw": None,
                                                    "recurse_mode": None,
                                                    "s3": None,
                                                    "sub_path": None,
                                                }
                                            ],
                                            "parameters": None,
                                        },
                                        "continue_on": None,
                                        "dependencies": None,
                                        "depends": "convert-to-artifact-0",
                                        "hooks": None,
                                        "inline": None,
                                        "name": "show-artifact-0",
                                        "on_exit": None,
                                        "template": "show-artifact",
                                        "template_ref": None,
                                        "when": None,
                                        "with_items": None,
                                        "with_param": None,
                                        "with_sequence": None,
                                    },
                                ],
                            },
                            "data": None,
                            "executor": None,
                            "fail_fast": None,
                            "host_aliases": None,
                            "http": None,
                            "init_containers": None,
                            "inputs": {"artifacts": None, "parameters": None},
                            "memoize": None,
                            "metadata": {"annotations": None, "labels": None},
                            "metrics": None,
                            "name": "bettmensch-ai-dag",
                            "node_selector": None,
                            "outputs": {
                                "artifacts": None,
                                "exit_code": None,
                                "parameters": None,
                                "result": None,
                            },
                            "parallelism": None,
                            "plugin": None,
                            "pod_spec_patch": None,
                            "priority": None,
                            "priority_class_name": None,
                            "resource": None,
                            "retry_strategy": None,
                            "scheduler_name": None,
                            "script": None,
                            "security_context": None,
                            "service_account_name": None,
                            "sidecars": None,
                            "steps": None,
                            "suspend": None,
                            "synchronization": None,
                            "timeout": None,
                            "tolerations": None,
                            "volumes": None,
                        },
                        {
                            "active_deadline_seconds": None,
                            "affinity": None,
                            "archive_location": None,
                            "automount_service_account_token": None,
                            "container": None,
                            "container_set": None,
                            "daemon": None,
                            "dag": None,
                            "data": None,
                            "executor": None,
                            "fail_fast": None,
                            "host_aliases": None,
                            "http": None,
                            "init_containers": None,
                            "inputs": {
                                "artifacts": None,
                                "parameters": [
                                    {
                                        "default": None,
                                        "description": None,
                                        "enum": None,
                                        "global_name": None,
                                        "name": "a",
                                        "value": None,
                                        "value_from": None,
                                    },
                                    {
                                        "default": "None",
                                        "description": None,
                                        "enum": None,
                                        "global_name": None,
                                        "name": "a_art",
                                        "value": None,
                                        "value_from": None,
                                    },
                                ],
                            },
                            "memoize": None,
                            "metadata": {"annotations": None, "labels": None},
                            "metrics": None,
                            "name": "convert-to-artifact",
                            "node_selector": None,
                            "outputs": {
                                "artifacts": [
                                    {
                                        "archive": None,
                                        "archive_logs": None,
                                        "artifact_gc": None,
                                        "artifactory": None,
                                        "azure": None,
                                        "deleted": None,
                                        "from_": None,
                                        "from_expression": None,
                                        "gcs": None,
                                        "git": None,
                                        "global_name": None,
                                        "hdfs": None,
                                        "http": None,
                                        "mode": None,
                                        "name": "a_art",
                                        "optional": None,
                                        "oss": None,
                                        "path": "a_art",
                                        "raw": None,
                                        "recurse_mode": None,
                                        "s3": None,
                                        "sub_path": None,
                                    }
                                ],
                                "exit_code": None,
                                "parameters": None,
                                "result": None,
                            },
                            "parallelism": None,
                            "plugin": None,
                            "pod_spec_patch": None,
                            "priority": None,
                            "priority_class_name": None,
                            "resource": None,
                            "retry_strategy": {
                                "affinity": None,
                                "backoff": None,
                                "expression": None,
                                "limit": "1",
                                "retry_policy": "OnError",
                            },
                            "scheduler_name": None,
                            "script": {
                                "args": None,
                                "command": ["python"],
                                "env": None,
                                "env_from": None,
                                "image": "bettmensch88/bettmensch.ai:3.11-latest",  # noqa: E501
                                "image_pull_policy": "Always",
                                "lifecycle": None,
                                "liveness_probe": None,
                                "name": "",
                                "ports": None,
                                "readiness_probe": None,
                                "resources": {
                                    "limits": {
                                        "cpu": "100m",
                                        "memory": "100Mi",
                                    },
                                    "requests": {
                                        "cpu": "100m",
                                        "memory": "100Mi",
                                    },
                                },
                                "security_context": None,
                                "source": "import os\nimport sys\nsys.path.append(os.getcwd())\n\n# --- preprocessing\nimport json\ntry: a = json.loads(r'''{{inputs.parameters.a}}''')\nexcept: a = r'''{{inputs.parameters.a}}'''\n\nfrom bettmensch_ai.io import InputParameter\n\nfrom bettmensch_ai.io import OutputArtifact\na_art = OutputArtifact(\"a_art\")\n\ndef convert_to_artifact(a: InputParameter, a_art: OutputArtifact=None) -> None:\n    \"\"\"When decorated with the bettmensch_ai.components.component decorator,\n    implements a bettmensch_ai.Component that converts its InputParameter into\n    an OutputArtifact.\"\"\"\n    with open(a_art.path, 'w') as a_art_file:\n        a_art_file.write(str(a))\nconvert_to_artifact(a,a_art)",  # noqa: E501
                                "startup_probe": None,
                                "stdin": None,
                                "stdin_once": None,
                                "termination_message_path": None,
                                "termination_message_policy": None,
                                "tty": None,
                                "volume_devices": None,
                                "volume_mounts": None,
                                "working_dir": None,
                            },
                            "security_context": None,
                            "service_account_name": None,
                            "sidecars": None,
                            "steps": None,
                            "suspend": None,
                            "synchronization": None,
                            "timeout": None,
                            "tolerations": None,
                            "volumes": None,
                        },
                        {
                            "active_deadline_seconds": None,
                            "affinity": None,
                            "archive_location": None,
                            "automount_service_account_token": None,
                            "container": None,
                            "container_set": None,
                            "daemon": None,
                            "dag": None,
                            "data": None,
                            "executor": None,
                            "fail_fast": None,
                            "host_aliases": None,
                            "http": None,
                            "init_containers": None,
                            "inputs": {
                                "artifacts": [
                                    {
                                        "archive": None,
                                        "archive_logs": None,
                                        "artifact_gc": None,
                                        "artifactory": None,
                                        "azure": None,
                                        "deleted": None,
                                        "from_": None,
                                        "from_expression": None,
                                        "gcs": None,
                                        "git": None,
                                        "global_name": None,
                                        "hdfs": None,
                                        "http": None,
                                        "mode": None,
                                        "name": "a",
                                        "optional": None,
                                        "oss": None,
                                        "path": "a",
                                        "raw": None,
                                        "recurse_mode": None,
                                        "s3": None,
                                        "sub_path": None,
                                    }
                                ],
                                "parameters": None,
                            },
                            "memoize": None,
                            "metadata": {"annotations": None, "labels": None},
                            "metrics": None,
                            "name": "show-artifact",
                            "node_selector": None,
                            "outputs": {
                                "artifacts": None,
                                "exit_code": None,
                                "parameters": None,
                                "result": None,
                            },
                            "parallelism": None,
                            "plugin": None,
                            "pod_spec_patch": None,
                            "priority": None,
                            "priority_class_name": None,
                            "resource": None,
                            "retry_strategy": {
                                "affinity": None,
                                "backoff": None,
                                "expression": None,
                                "limit": "1",
                                "retry_policy": "OnError",
                            },
                            "scheduler_name": None,
                            "script": {
                                "args": None,
                                "command": ["python"],
                                "env": None,
                                "env_from": None,
                                "image": "bettmensch88/bettmensch.ai:3.11-latest",  # noqa: E501
                                "image_pull_policy": "Always",
                                "lifecycle": None,
                                "liveness_probe": None,
                                "name": "",
                                "ports": None,
                                "readiness_probe": None,
                                "resources": {
                                    "limits": {
                                        "cpu": "100m",
                                        "memory": "100Mi",
                                    },
                                    "requests": {
                                        "cpu": "100m",
                                        "memory": "100Mi",
                                    },
                                },
                                "security_context": None,
                                "source": 'import os\nimport sys\nsys.path.append(os.getcwd())\n\n# --- preprocessing\nimport json\n\nfrom bettmensch_ai.io import InputArtifact\na = InputArtifact("a")\n\ndef show_artifact(a: InputArtifact) -> None:\n    """When decorated with the bettmensch_ai.components.component decorator,\n    implements a bettmensch_ai.Component that prints the values of its\n    InputArtifact."""\n    with open(a.path, \'r\') as a_art_file:\n        a_content = a_art_file.read()\n    print(f\'Content of input artifact a: {a_content}\')\nshow_artifact(a)',  # noqa: E501
                                "startup_probe": None,
                                "stdin": None,
                                "stdin_once": None,
                                "termination_message_path": None,
                                "termination_message_policy": None,
                                "tty": None,
                                "volume_devices": None,
                                "volume_mounts": None,
                                "working_dir": None,
                            },
                            "security_context": None,
                            "service_account_name": None,
                            "sidecars": None,
                            "steps": None,
                            "suspend": None,
                            "synchronization": None,
                            "timeout": None,
                            "tolerations": None,
                            "volumes": None,
                        },
                    ],
                    "tolerations": None,
                    "ttl_strategy": None,
                    "volume_claim_gc": None,
                    "volume_claim_templates": None,
                    "volumes": None,
                    "workflow_metadata": None,
                    "workflow_template_ref": None,
                },
            }

    return MockHeraWorkflowTemplateModel()
