apiVersion: v1
kind: Secret
metadata:
  name: my-s3-cred
  namespace: argo
type: Opaque
data:
  accesskey: "echo -n {access_key_id goes here} | base64"
  secretkey: "echo -n {secrret_access_key goes here} | base64"