apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-server
  namespace: mlflow
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::743582000746:role/bettmensch-ai-artifact-role
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow-server
  name: mlflow-server
  namespace: mlflow
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: tracking-server
  selector:
    app: mlflow-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
  labels:
      app: mlflow-server
spec:
  # The replica count is kept to one for simplicity purposes.
  # To create a highly available app, the replica count would
  # be higher.
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      serviceAccountName: mlflow-server
      containers:
        - name: mlflow-tracking-server
          image: ghcr.io/mlflow/mlflow:v2.17.0
          imagePullPolicy: Always
          # use local storage for meta data and artifacts to start off
          command: ["/bin/sh","-c"]
          args: ["pip install boto3 && mlflow server --backend-store-uri /mlflow --default-artifact-root s3://bettmensch-ai-artifact-repository/mlflow --host 0.0.0.0 --port 5000"]
          ports:
            - name: tracking-server
              containerPort: 5000