apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: on-demand-cpu
spec:
  template:
    spec:
      nodeClassRef:
        name: bettmensch-ai-default
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["c4.large","c4.xlarge","c4.2xlarge","c4.4xlarge","c5.large","c5.xlarge","c5.2xlarge","c5.4xlarge"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
  limits:
    cpu: 100
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 15m # ~5 minutes required for larger images, otherwise karpenter will deprovision before pods are running
    expireAfter: 1h
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: short-run-gpu
spec:
  template:
    spec:
      nodeClassRef:
        name: bettmensch-ai-default
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["g4dn.xlarge","g4dn.2xlarge","g4ad.xlarge","ga4d.2xlarge","ga4d.4xlarge","g6.xlarge","g3s.xlarge","ga4d.8xlarge","ga4d.16xlarge"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot","on-demand"]
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: "NoSchedule"
  limits:
    cpu: 100
    memory: 1000Gi
    nvidia.com/gpu: 8
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 15m # dont go lower to prevent decomissioning bc of image pull phase
    expireAfter: 1h # limit GPU nodes to 1 hour - enough to train annotated transformer on 4 GPUs (~2.8h on 1 GPU)
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: long-run-gpu
spec:
  template:
    spec:
      nodeClassRef:
        name: bettmensch-ai-default
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["g4dn.xlarge","g4dn.2xlarge","g4ad.xlarge","ga4d.2xlarge","ga4d.4xlarge","g6.xlarge","g3s.xlarge","ga4d.8xlarge","ga4d.16xlarge"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: "NoSchedule"
        - key: long-run-gpu
          value: "true"
          effect: NoSchedule
  limits:
    cpu: 200
    memory: 2000Gi
    nvidia.com/gpu: 8
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30m # larger training images take longer to pull
    expireAfter: 12h # limit GPU nodes to 12h hours
