apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test_component
  namespace: argo
spec:
  arguments:
    parameters:
    - name: a
    - name: b
    - name: c
  entrypoint: test_dag
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: a
            value: '{{workflow.parameters.a}}'
          - name: b
            value: '{{workflow.parameters.b}}'
        depends: add-0
        name: add-0
        template: add
      - arguments:
          parameters:
          - name: a
            value: '{{tasks.add-0.outputs.parameters.sum}}'
          - name: b
            value: '{{workflow.parameters.c}}'
        depends: add-0
        name: add-1
        template: add
    name: test_dag
  - inputs:
      parameters:
      - default: '1'
        name: a
      - default: '2'
        name: b
      - default: 'null'
        name: sum
    name: add
    outputs:
      parameters:
      - name: sum
        valueFrom:
          path: ./temp/outputs\sum
    script:
      command:
      - python
      image: python:3.8
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())

        # --- preprocessing
        import json
        try: a = json.loads(r'''{{inputs.parameters.a}}''')
        except: a = r'''{{inputs.parameters.a}}'''
        try: b = json.loads(r'''{{inputs.parameters.b}}''')
        except: b = r'''{{inputs.parameters.b}}'''

        from bettmensch_ai.arguments import ComponentOutput
        sum = ComponentOutput("sum")

        sum.assign(a + b)
