apiVersion: v1
kind: Secret
metadata:
  name: my-s3-cred
  namespace: argo
type: Opaque
data:
  accesskey: "echo -n {access_key_id} | base64"
  secretkey: "echo -n {secrret_access_key} | base64"
---
apiVersion: v1
data:
  bettmensch-ai-artifact-repository: |
    s3:
      bucket: bettmensch-ai-pipelines
      endpoint: s3.amazonaws.com
      insecure: true
      accessKeySecret:
        name: my-s3-cred
        key: accesskey
      secretKeySecret:
        name: my-s3-cred
        key: secretkey
kind: ConfigMap
metadata:
  annotations:
    workflows.argoproj.io/default-artifact-repository: bettmensch-ai-artifact-repository
  name: artifact-repositories
  namespace: argo
