apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: pipeline-test-pipeline-
  namespace: argo
spec:
  arguments:
    parameters:
    - name: a
      value: '1'
    - name: b
      value: '2'
    - name: c
      value: '3'
  entrypoint: bettmensch-ai-dag
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: a
            value: '{{workflow.parameters.a}}'
          - name: b
            value: '{{workflow.parameters.b}}'
        depends: ''
        name: add-0
        template: add
      - arguments:
          parameters:
          - name: a
            value: '{{tasks.add-0.outputs.parameters.sum}}'
          - name: b
            value: '{{workflow.parameters.c}}'
        depends: add-0
        name: add-1
        template: add
      - arguments:
          parameters:
          - name: a
            value: '{{tasks.add-1.outputs.parameters.sum}}'
          - name: b
            value: '{{tasks.add-1.outputs.parameters.sum}}'
        depends: add-1
        name: add-2
        template: add
    name: bettmensch-ai-dag
  - inputs:
      parameters:
      - name: a
      - name: b
      - default: 'null'
        name: sum
    name: add
    outputs:
      parameters:
      - name: sum
        valueFrom:
          path: ./temp/outputs/sum
    script:
      command:
      - python
      image: bettmensch88/bettmensch.ai:3.11
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())

        # --- preprocessing
        import json
        try: a = json.loads(r'''{{inputs.parameters.a}}''')
        except: a = r'''{{inputs.parameters.a}}'''
        try: b = json.loads(r'''{{inputs.parameters.b}}''')
        except: b = r'''{{inputs.parameters.b}}'''

        from bettmensch_ai.arguments import ComponentOutput
        sum = ComponentOutput("sum")

        sum.assign(a + b)
