on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    # Sequence of patterns matched against refs/heads
    branches:
      - master
  push:
    branches:
      - master

jobs:
  sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11",]

    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/workflows/unit-test.yaml
        with:
          python-version: ${{ matrix.python-version }}

      - uses: ./.github/workflows/integration-test.yaml
        with:
          python-version: ${{ matrix.python-version }}

  docker-components:
    runs-on: ubuntu-latest
    needs: sdk
    strategy:
      matrix:
        component: ["standard", "pytorch", "pytorch-lightning"]

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build component image
        run: make component.build COMPONENT=${{ matrix.component }}
      - name: Tag and push component image
        if: ${{ github.event_name == 'push' }}
        run: make component.push COMPONENT=${{ matrix.component }}

  docker-dashboard:
    runs-on: ubuntu-latest
    needs: sdk
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build component image
        run: make dashboard.build
      - name: Tag and push component image
        if: ${{ github.event_name == 'push' }}
        run: make dashboard.push