on:
  workflow_dispatch:
    inputs:
      test-flags:
        default: "" # for the k8s test suite: "-m standard", "-m ddp" etc
        required: false
        type: choice
        options:
        - ""
        - "-m standard"
        - "-m ddp"
        - "-m delete_pipelines"
        - "-m delete_flows"

      python-version:
        default: "3.10" # "3.11"
        required: false
        type: choice
        options:
        - "3.10"
        - "3.11"
        - "3.12"
        
jobs:
  k8s-test:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/test.yaml
    with:
      test-suite: k8s
      test-flags: ${{ inputs.test-flags }}
      python-version: ${{ inputs.python-version }}