on:
  workflow_dispatch:
    inputs:
      test-flags:
        default: "" # for the k8s test suite: "-m standard", "-m ddp" etc
        required: false
        type: choice
        options:
        - ""
        - "-m standard"
        - "-m ddp"
        - "-m delete_pipelines"
        - "-m delete_flows"

      python-version:
        default: "3.10" # "3.11"
        required: false
        type: choice
        options:
        - "3.10"
        - "3.11"
        - "3.12"

      deprovision-when-finished:
        default: false
        required: false
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  k8s-test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      test-suite: k8s
      test-flags: ${{ inputs.test-flags }}
      python-version: ${{ inputs.python-version }}