name: Scheduled platform test
on:
  schedule:
    - cron: '50 16 * * *' # run this test at 16:40 UTC every day
jobs:
  k8s-test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      test-suite: k8s
      test-flags: ""
      python-version: "3.10"
      deprovision-when-finished: true