on:
  workflow_call:
    inputs:
      test-suite:
        default: "unit" # "integration", "k8s"
        required: true
        type: string
      test-flags:
        default: "" # for the k8s test suite: "-m standard", "-m ddp" etc
        required: false
        type: string 
      python-version:
        default: "3.10" # "3.11"
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        if: ${{ inputs.test-suite == 'k8s' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
        
      - name: Connect to platform
        if: ${{ inputs.test-suite == 'k8s' }}
        run: make platform.connect

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      
      - name: Installation setup
        run: pip install setuptools
      
      - name: Install sdk
        run: make sdk.install EXTRAS=test
      
      - name: Run test suite
        run: make sdk.test SUITE="${{ inputs.test-suite }}" PYTEST_FLAGS="${{ inputs.test-flags }}"