on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    # Sequence of patterns matched against refs/heads
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit-test-py310:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      test-suite: unit
      python-version: "3.10"

  unit-test-py311:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      test-suite: unit
      python-version: "3.11"